### PR TITLE
Default to min/max KPI bounds if not given

### PR DESCRIPTION
**Pull request by arurke**
As in title.

### CODE REVIEW

**Comment by romain-jacob** [comment]
Awesome, I even gets my to-dos worked on! :-) Thanks a lot!

**Comment by arurke** [comment]
Hehe, yeah it got in my way 😄

**Comment by arurke** [comment]
@romain-jacob hijacking this for a quick question: Have you considered enabling discussions on Github as opposed to the [google group](https://groups.google.com/g/triscale)? Seems there is not too much activity there (although not too much traffic on github either), but it might be more accessible with everything gathered at one place? Or alternatively, add a link to the google group in the README?

**Comment by romain-jacob** [comment]
Fair question. The answer is simple: I was not aware of that feature. I do like the idea of using fewer tools though, so I must say I like the suggestion quite a bit. 

Will update that :-)

**Comment by romain-jacob** [comment]
Actually, I just notice now your question on the GG... I don't understand why right now, but somehow I didn't get notified :-/

**Comment by romain-jacob** [comment]
I let you re-post your question as a Discussion, and I'll answer there, as to kickstart the "new mode of communication." 

I do understand your question, which is indeed a tricky one, and there are a lot to say about it imo ;-)

**Comment by arurke** [comment]
> I was not aware of that feature.

It is quite new (summer/autumn 2021) so I don't blame you. I noticed it on contiki-ng and it works reasonably well there.

> I let you re-post your question as a Discussion, and I'll answer there, as to kickstart the "new mode of communication." I do understand your question, which is indeed a tricky one, and there is a lot to say about it imo ;-)

👍 Looking forward to your thoughts!

**Pull request merged**
